from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN
from pptx.dml.color import RGBColor
class PresentationWriter:
    """
    ORION Presentation Engine
    -------------------------
    Generates professional 12-slide decks.
    """

    @staticmethod
    def create_deck(topic, outline, content_map, output_path):
        prs = Presentation()

        # Define Colors
        DARK_BG = RGBColor(20, 24, 35)      # Dark Slate/Blue
        ACCENT_COLOR = RGBColor(0, 255, 200) # Cyan/Teal
        TEXT_COLOR = RGBColor(240, 240, 240) # Off-White

        def apply_dark_theme(slide):
            # Set Background Color
            background = slide.background
            fill = background.fill
            fill.solid()
            fill.fore_color.rgb = DARK_BG

        # 1. Title Slide
        slide = prs.slides.add_slide(prs.slide_layouts[0])
        apply_dark_theme(slide)

        title = slide.shapes.title
        subtitle = slide.placeholders[1]

        title.text = topic.replace("_", " ").upper()
        subtitle.text = "Generated by ORION AI"

        # Style Title
        title.text_frame.paragraphs[0].font.size = Pt(54)
        title.text_frame.paragraphs[0].font.bold = True
        title.text_frame.paragraphs[0].font.color.rgb = ACCENT_COLOR
        title.text_frame.paragraphs[0].font.name = "Calibri"

        subtitle.text_frame.paragraphs[0].font.color.rgb = TEXT_COLOR
        subtitle.text_frame.paragraphs[0].font.size = Pt(24)

        # 2. Content Slides
        slide_layout = prs.slide_layouts[1] # Title + Content

        for i, section in enumerate(outline[:12]):
            if section not in content_map: continue

            # Create slide
            slide = prs.slides.add_slide(slide_layout)
            apply_dark_theme(slide)

            # Title Styling
            title_shape = slide.shapes.title

            # Clean Title: Remove numbering and underscores
            clean_title = section.lstrip("0123456789.- ").strip().replace("_", " ")
            title_shape.text = clean_title

            title_shape.text_frame.paragraphs[0].font.size = Pt(40)
            title_shape.text_frame.paragraphs[0].font.bold = True
            title_shape.text_frame.paragraphs[0].font.color.rgb = ACCENT_COLOR
            title_shape.text_frame.paragraphs[0].font.name = "Calibri"
            title_shape.text_frame.paragraphs[0].alignment = PP_ALIGN.LEFT

            # Add a decorative line under title
            left = Inches(0.5)
            top = Inches(1.5)
            width = Inches(9)
            height = Inches(0.05)
            line = slide.shapes.add_shape(1, left, top, width, height) # 1 = Rectangle
            line.fill.solid()
            line.fill.fore_color.rgb = ACCENT_COLOR
            line.line.fill.background() # No border

            # Content Styling
            tf = slide.placeholders[1].text_frame
            points = content_map[section]

            tf.clear() # Clear default empty paragraph

            # Reposition Text Box to sit under the decorative line
            slide.placeholders[1].left = Inches(0.5)
            slide.placeholders[1].top = Inches(1.8)
            slide.placeholders[1].width = Inches(9)

            for point in points[:6]: # Max 6 bullets
                # Sanitization
                clean_point = point.lstrip("- ").strip()
                if "Here are the bullet points" in clean_point: continue
                if clean_point.lower() == clean_title.lower(): continue
                clean_point = clean_point.replace("_", " ")

                p = tf.add_paragraph()
                p.text = clean_point
                p.level = 0
                p.font.size = Pt(15)
                p.font.name = "Calibri"
                p.font.color.rgb = TEXT_COLOR
                p.space_after = Pt(14)

        # 3. Thank You Slide
        slide = prs.slides.add_slide(prs.slide_layouts[2])
        apply_dark_theme(slide)

        title = slide.shapes.title
        title.text = "Thank You"
        title.text_frame.paragraphs[0].font.color.rgb = ACCENT_COLOR
        title.text_frame.paragraphs[0].font.size = Pt(54)

        if len(slide.placeholders) > 1:
            sub = slide.placeholders[1]
            sub.text = "Generated by ORION"
            sub.text_frame.paragraphs[0].font.color.rgb = TEXT_COLOR

        prs.save(output_path)
        return output_path
